backend:
  name: github
  repo: AlexGoodNews/alex-capricho
  branch: main # Branch to update (optional; defaults to master)
  site_domain: https://alex-capricho.pages.dev/
  base_url: https://alex-capricho.pages.dev/
  auth_endpoint: /api/auth
media_folder: static/img
public_folder: /img

collections:
  - name: "puntos"
    label: "Puntos del Museo"
    files:
      - name: "puntos"
        label: "Puntos"
        file: "data/puntos.json"
        fields:
          - label: "Lista de puntos"
            name: "puntos"
            widget: "list"
            fields:
              - { label: "ID", name: "id", widget: "string" }

              - label: "Nombre"
                name: "nombre"
                widget: "object"
                fields:
                  - { label: "ES", name: "es", widget: "string" }
                  - { label: "EN", name: "en", widget: "string" }

              - label: "Descripción"
                name: "descripcion"
                widget: "object"
                fields:
                  - { label: "ES", name: "es", widget: "text" }
                  - { label: "EN", name: "en", widget: "text" }

              - label: "Coordenadas"
                name: "coords"
                widget: "list"
                allow_add: true
                required: false

              - { label: "Accesible", name: "accesible", widget: "boolean", required: false, default: false }

              - label: "Media"
                name: "media"
                widget: "object"
                fields:
                  - { label: "Audio ES", name: "audio_es", widget: "file", required: false, default: "" }
                  - { label: "Audio EN", name: "audio_en", widget: "file", required: false, default: "" }
                  - { label: "Video Signos", name: "video_signos", widget: "file", required: false, default: "" }

